package com.abhiram.stocktrader.dto;

import lombok.AllArgsConstructor;
import lombok.Data;

/**
 * Represents calculated portfolio analytics.
 *
 * These analytics are generated by the backend
 * and later interpreted by the AI advisor.
 */
@Data
@AllArgsConstructor
public class PortfolioAnalyticsResponse {

    /**
     * Overall portfolio risk score (0-10).
     */
    private double overallRiskScore;

    /**
     * Diversification risk (0-100).
     */
    private double diversificationScore;

    /**
     * Portfolio concentration risk (0-100).
     */
    private double concentrationScore;

    /**
     * Liquidity risk (0-100).
     */
    private double liquidityScore;

    /**
     * Volatility risk (0-100).
     * Placeholder until historical data is added.
     */
    private double volatilityScore;

    /**
     * Largest holding percentage.
     */
    private double largestHoldingPercentage;

    /**
     * Percentage of account held as cash.
     */
    private double cashAllocation;

    /**
     * Number of different stocks owned.
     */
    private int numberOfHoldings;

    /**
     * Overall unrealized profit/loss
     * across the portfolio.
     */
    private double unrealizedGainLoss;

    /**
     * Overall unrealized return percentage.
     */
    private double unrealizedReturnPercentage;

    /**
     * Human-readable risk category.
     */
    private String riskCategory;
}