package com.abhiram.stocktrader.dto;

import lombok.AllArgsConstructor;
import lombok.Data;

/**
 * Stores calculated portfolio risk metrics.
 * These values are generated by the backend
 * and later explained by the AI model.
 */
@Data
@AllArgsConstructor
public class RiskScoreResponse {

    /**
     * Overall portfolio risk score (0-10).
     */
    private double riskScore;

    /**
     * Percentage of account held as cash.
     */
    private double cashAllocation;

    /**
     * Percentage represented by the largest holding.
     */
    private double largestHoldingPercentage;

    /**
     * Number of different stocks owned.
     */
    private int numberOfHoldings;
}